# Generated by Django 4.2.21 on 2026-02-11 19:25

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actaseguimiento',
            name='resumen_indicadores',
            field=models.JSONField(blank=True, default=dict, validators=[apps.core.validators.resumen_indicadores_validator], verbose_name='Resumen de indicadores'),
        ),
    ]
