# Generated by Django 5.1.15 on 2026-01-27 02:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tramo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('codigo', models.CharField(help_text='Código único del tramo (ej: TRM-001)', max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(help_text='Nombre descriptivo del tramo (ej: Sector Norte)', max_length=100, verbose_name='Nombre')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tramos', to='lineas.linea', verbose_name='Línea')),
                ('torre_fin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tramos_fin', to='lineas.torre', verbose_name='Torre fin')),
                ('torre_inicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tramos_inicio', to='lineas.torre', verbose_name='Torre inicio')),
            ],
            options={
                'verbose_name': 'Tramo',
                'verbose_name_plural': 'Tramos',
                'db_table': 'tramos',
                'ordering': ['linea', 'codigo'],
            },
        ),
    ]
