# Generated by Django 5.1.15 on 2026-01-27 02:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrillas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('fecha', models.DateField(help_text='Fecha del registro de asistencia', verbose_name='Fecha')),
                ('tipo_novedad', models.CharField(choices=[('PRESENTE', 'Presente'), ('VACACIONES', 'Vacaciones'), ('INCAPACIDAD', 'Incapacidad'), ('PERMISO', 'Permiso'), ('AUSENTE', 'Ausente'), ('LICENCIA', 'Licencia'), ('CAPACITACION', 'Capacitación')], default='PRESENTE', max_length=20, verbose_name='Tipo de novedad')),
                ('hora_entrada', models.TimeField(blank=True, null=True, verbose_name='Hora de entrada')),
                ('hora_salida', models.TimeField(blank=True, null=True, verbose_name='Hora de salida')),
                ('observacion', models.TextField(blank=True, help_text='Observaciones adicionales sobre la asistencia', verbose_name='Observación')),
                ('cuadrilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='cuadrillas.cuadrilla', verbose_name='Cuadrilla')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Asistencia',
                'verbose_name_plural': 'Asistencias',
                'db_table': 'asistencias',
                'ordering': ['-fecha', 'cuadrilla', 'usuario'],
                'indexes': [models.Index(fields=['fecha'], name='asistencias_fecha_d405d2_idx'), models.Index(fields=['cuadrilla', 'fecha'], name='asistencias_cuadril_d46c33_idx'), models.Index(fields=['tipo_novedad'], name='asistencias_tipo_no_a2a895_idx')],
                'unique_together': {('usuario', 'cuadrilla', 'fecha')},
            },
        ),
    ]
