# Generated by Django 4.2.21 on 2026-02-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrillas', '0004_cuadrilla_fecha_cuadrillamiembro_costo_dia'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='viaticos',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costo de viáticos del día', max_digits=12, verbose_name='Viáticos'),
        ),
    ]
