# Generated by Django 5.1.15 on 2026-02-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrillas', '0005_asistencia_viaticos'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='horas_extra',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='Horas extra trabajadas en el día', max_digits=4, verbose_name='Horas extra'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='viatico_aplica',
            field=models.BooleanField(default=False, help_text='Indica si el día aplica viático (Sí/No)', verbose_name='Viático aplica'),
        ),
    ]
