# Generated by Django 5.2.11 on 2026-02-20 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadrillas', '0007_add_new_roles_to_cuadrilla_miembro'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='he_diurna',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='Horas extra diurnas', max_digits=4, verbose_name='HE Diurna'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='he_dominical_diurna',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='Horas extra dominicales diurnas', max_digits=4, verbose_name='HE Dom. Diurna'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='he_dominical_nocturna',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='Horas extra dominicales nocturnas', max_digits=4, verbose_name='HE Dom. Nocturna'),
        ),
        migrations.AddField(
            model_name='asistencia',
            name='he_nocturna',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='Horas extra nocturnas', max_digits=4, verbose_name='HE Nocturna'),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='horas_extra',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, help_text='Total horas extra (auto-calculado)', max_digits=4, verbose_name='Horas extra'),
        ),
    ]
