# Generated by Django 4.2.21 on 2026-02-11 19:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lineas', '0003_linea_transelca_fields'),
        ('ambiental', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informeambiental',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='informeambiental',
            name='estado',
            field=models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En Revisión'), ('APROBADO', 'Aprobado'), ('ENVIADO', 'Enviado al Cliente'), ('RECHAZADO', 'Rechazado')], default='BORRADOR', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='informeambiental',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha aprobación'),
        ),
        migrations.AlterField(
            model_name='informeambiental',
            name='fecha_elaboracion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha elaboración'),
        ),
        migrations.AlterField(
            model_name='informeambiental',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha envío'),
        ),
        migrations.AlterField(
            model_name='informeambiental',
            name='fecha_revision',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha revisión'),
        ),
        migrations.AlterField(
            model_name='informeambiental',
            name='hectareas_intervenidas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Hectáreas intervenidas'),
        ),
        migrations.AlterField(
            model_name='informeambiental',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='informeambiental',
            name='linea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes_ambientales', to='lineas.linea', verbose_name='Línea'),
        ),
        migrations.AlterField(
            model_name='informeambiental',
            name='m3_vegetacion',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='M³ vegetación removida'),
        ),
        migrations.AlterField(
            model_name='informeambiental',
            name='periodo_anio',
            field=models.PositiveIntegerField(verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='informeambiental',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='permisoservidumbre',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='permisoservidumbre',
            name='fecha_autorizacion',
            field=models.DateField(verbose_name='Fecha de autorización'),
        ),
        migrations.AlterField(
            model_name='permisoservidumbre',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='permisoservidumbre',
            name='predio_matricula',
            field=models.CharField(blank=True, max_length=50, verbose_name='Matrícula inmobiliaria'),
        ),
        migrations.AlterField(
            model_name='permisoservidumbre',
            name='propietario_telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='permisoservidumbre',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
    ]
