# Generated by Django 4.2.21 on 2026-02-11 19:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lineas', '0003_linea_transelca_fields'),
        ('financiero', '0002_costoactividad'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ciclofacturacion',
            options={'ordering': ['-created_at'], 'verbose_name': 'Ciclo de Facturación', 'verbose_name_plural': 'Ciclos de Facturación'},
        ),
        migrations.AlterModelOptions(
            name='ejecucioncosto',
            options={'ordering': ['-fecha'], 'verbose_name': 'Ejecución de Costo', 'verbose_name_plural': 'Ejecución de Costos'},
        ),
        migrations.AlterField(
            model_name='ciclofacturacion',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='ciclofacturacion',
            name='estado',
            field=models.CharField(choices=[('INFORME_GENERADO', 'Informe Generado'), ('EN_VALIDACION', 'En Validación Cliente'), ('ORDEN_ENTREGA', 'Orden de Entrega'), ('FACTURA_EMITIDA', 'Factura Emitida'), ('PAGO_RECIBIDO', 'Pago Recibido')], default='INFORME_GENERADO', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ciclofacturacion',
            name='fecha_validacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha validación'),
        ),
        migrations.AlterField(
            model_name='ciclofacturacion',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ciclofacturacion',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número de factura'),
        ),
        migrations.AlterField(
            model_name='ciclofacturacion',
            name='numero_orden',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número orden de entrega'),
        ),
        migrations.AlterField(
            model_name='ciclofacturacion',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='costoactividad',
            name='costo_vehiculos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Costo vehículos'),
        ),
        migrations.AlterField(
            model_name='costoactividad',
            name='costo_viaticos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Costo viáticos'),
        ),
        migrations.AlterField(
            model_name='costoactividad',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='costoactividad',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='costoactividad',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='costorecurso',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='costorecurso',
            name='descripcion',
            field=models.CharField(max_length=200, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='costorecurso',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='costorecurso',
            name='tipo',
            field=models.CharField(choices=[('DIA_HOMBRE', 'Día Hombre'), ('VEHICULO', 'Vehículo'), ('VIATICO', 'Viático'), ('HERRAMIENTA', 'Herramienta'), ('MATERIAL', 'Material'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de recurso'),
        ),
        migrations.AlterField(
            model_name='costorecurso',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='ejecucioncosto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='ejecucioncosto',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ejecucioncosto',
            name='tipo_recurso',
            field=models.CharField(choices=[('DIA_HOMBRE', 'Día Hombre'), ('VEHICULO', 'Vehículo'), ('VIATICO', 'Viático'), ('HERRAMIENTA', 'Herramienta'), ('MATERIAL', 'Material'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de recurso'),
        ),
        migrations.AlterField(
            model_name='ejecucioncosto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='anio',
            field=models.PositiveIntegerField(verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='costo_dias_hombre',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Costo días hombre'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='costo_vehiculos',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Costo vehículos'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='dias_hombre_planeados',
            field=models.PositiveIntegerField(default=0, verbose_name='Días hombre planeados'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='dias_vehiculo_planeados',
            field=models.PositiveIntegerField(default=0, verbose_name='Días vehículo planeados'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='estado',
            field=models.CharField(choices=[('PROYECTADO', 'Proyectado'), ('APROBADO', 'Aprobado'), ('EN_EJECUCION', 'En Ejecución'), ('CERRADO', 'Cerrado')], default='PROYECTADO', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='facturacion_esperada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Facturación esperada'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='linea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='lineas.linea', verbose_name='Línea'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='presupuesto',
            name='viaticos_planeados',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Viáticos planeados'),
        ),
    ]
