# Generated by Django 5.1.15 on 2026-02-16 15:35

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0005_remove_informediario_unique_informe_fecha_cuadrilla_and_more'),
        ('financiero', '0003_alter_ciclofacturacion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistFacturacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('facturado', models.BooleanField(default=False, verbose_name='Facturado')),
                ('fecha_facturacion', models.DateField(blank=True, null=True, verbose_name='Fecha de facturacion')),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_facturacion', to='actividades.actividad', verbose_name='Actividad')),
                ('ciclo_facturacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checklist_items', to='financiero.ciclofacturacion', verbose_name='Ciclo de facturacion')),
            ],
            options={
                'verbose_name': 'Checklist de Facturacion',
                'verbose_name_plural': 'Checklists de Facturacion',
                'db_table': 'checklist_facturacion',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['facturado'], name='checklist_f_factura_a8119e_idx'), models.Index(fields=['actividad'], name='checklist_f_activid_8e2b80_idx')],
            },
        ),
    ]
