# Generated by Django 5.1.15 on 2026-02-18 00:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiero', '0004_checklistfacturacion'),
        ('lineas', '0001_initial'),
    ]

    operations = [
        # Add numero_factura to ChecklistFacturacion
        migrations.AddField(
            model_name='checklistfacturacion',
            name='numero_factura',
            field=models.CharField(blank=True, max_length=50, verbose_name='Numero de factura'),
        ),
        # Create ArchivoChecklist model
        migrations.CreateModel(
            name='ArchivoChecklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('archivo', models.FileField(upload_to='facturacion/checklist/', verbose_name='Archivo')),
                ('nombre_original', models.CharField(max_length=255, verbose_name='Nombre original')),
                ('tipo_archivo', models.CharField(blank=True, max_length=50, verbose_name='Tipo de archivo')),
                ('tamanio', models.PositiveIntegerField(default=0, verbose_name='Tamano (bytes)')),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='financiero.checklistfacturacion', verbose_name='Checklist')),
            ],
            options={
                'verbose_name': 'Archivo de Checklist',
                'verbose_name_plural': 'Archivos de Checklist',
                'db_table': 'archivos_checklist',
                'ordering': ['-created_at'],
            },
        ),
        # Create ArchivoPeriodoFacturacion model
        migrations.CreateModel(
            name='ArchivoPeriodoFacturacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('anio', models.PositiveIntegerField(verbose_name='Ano')),
                ('mes', models.PositiveIntegerField(verbose_name='Mes')),
                ('archivo', models.FileField(upload_to='facturacion/periodos/', verbose_name='Archivo')),
                ('nombre_original', models.CharField(max_length=255, verbose_name='Nombre original')),
                ('descripcion', models.CharField(blank=True, max_length=200, verbose_name='Descripcion')),
                ('tipo_archivo', models.CharField(blank=True, max_length=50, verbose_name='Tipo de archivo')),
                ('tamanio', models.PositiveIntegerField(default=0, verbose_name='Tamano (bytes)')),
                ('linea', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archivos_facturacion', to='lineas.linea', verbose_name='Linea')),
            ],
            options={
                'verbose_name': 'Archivo de Periodo de Facturacion',
                'verbose_name_plural': 'Archivos de Periodo de Facturacion',
                'db_table': 'archivos_periodo_facturacion',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['anio', 'mes'], name='idx_archivo_periodo')],
            },
        ),
    ]
