# Generated by Django 4.2.21 on 2026-02-11 19:25

import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campo', '0003_registrocampo_avance_pendientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidencia',
            name='metadata_exif',
            field=models.JSONField(blank=True, default=dict, validators=[apps.core.validators.metadata_exif_validator], verbose_name='Metadata EXIF'),
        ),
        migrations.AlterField(
            model_name='evidencia',
            name='validacion_ia',
            field=models.JSONField(blank=True, default=dict, help_text='Resultado de validación: nitidez, iluminación, válida', validators=[apps.core.validators.validacion_ia_validator], verbose_name='Validación IA'),
        ),
        migrations.AlterField(
            model_name='registrocampo',
            name='datos_formulario',
            field=models.JSONField(blank=True, default=dict, help_text='Datos capturados según el tipo de actividad', validators=[apps.core.validators.datos_formulario_validator], verbose_name='Datos del formulario'),
        ),
    ]
