# Generated by Django 4.2.21 on 2026-02-11 19:24

import apps.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lineas', '0003_linea_transelca_fields'),
        ('cuadrillas', '0004_cuadrilla_fecha_cuadrillamiembro_costo_dia'),
        ('actividades', '0004_informediario'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='informediario',
            name='unique_informe_fecha_cuadrilla',
        ),
        migrations.RenameIndex(
            model_name='informediario',
            new_name='informes_di_fecha_66c661_idx',
            old_name='informes_di_fecha_3b9c2f_idx',
        ),
        migrations.RenameIndex(
            model_name='informediario',
            new_name='informes_di_cuadril_14c88c_idx',
            old_name='informes_di_cuadril_a8e721_idx',
        ),
        migrations.RenameIndex(
            model_name='informediario',
            new_name='informes_di_linea_i_e32a36_idx',
            old_name='informes_di_linea_i_c7d8f3_idx',
        ),
        migrations.RenameIndex(
            model_name='informediario',
            new_name='informes_di_estado_726da3_idx',
            old_name='informes_di_estado_49c3e2_idx',
        ),
        migrations.AddField(
            model_name='actividad',
            name='comentarios_restricciones',
            field=models.TextField(blank=True, help_text='Restricciones operativas, accesos, permisos o notas del campo', verbose_name='Comentarios / Restricciones'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='numero_consignacion',
            field=models.CharField(blank=True, help_text='Número de consignación asignado por el operador', max_length=30, verbose_name='Número de consignación'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='orden_sap',
            field=models.CharField(blank=True, help_text='Número de orden de trabajo en SAP', max_length=20, verbose_name='Número Orden SAP'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='pt_sap',
            field=models.CharField(blank=True, help_text='Código del puesto de trabajo SAP', max_length=20, verbose_name='Puesto Trabajo SAP'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='requiere_consignacion',
            field=models.BooleanField(default=False, help_text='Indica si la actividad requiere consignación del circuito', verbose_name='Requiere consignación'),
        ),
        migrations.AlterField(
            model_name='informediario',
            name='condicion_climatica',
            field=models.CharField(choices=[('SOLEADO', 'Soleado'), ('NUBLADO', 'Nublado'), ('LLUVIOSO', 'Lluvioso'), ('TORMENTA', 'Tormenta Eléctrica')], default='SOLEADO', max_length=20, verbose_name='Condición climática'),
        ),
        migrations.AlterField(
            model_name='informediario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='informediario',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de aprobación'),
        ),
        migrations.AlterField(
            model_name='informediario',
            name='fecha_envio',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío'),
        ),
        migrations.AlterField(
            model_name='informediario',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='informediario',
            name='linea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes_diarios', to='lineas.linea', verbose_name='Línea'),
        ),
        migrations.AlterField(
            model_name='informediario',
            name='novedades',
            field=models.TextField(blank=True, help_text='Novedades o incidentes del día', verbose_name='Novedades'),
        ),
        migrations.AlterField(
            model_name='informediario',
            name='resumen_trabajo',
            field=models.TextField(blank=True, help_text='Descripción detallada del trabajo realizado', verbose_name='Resumen del trabajo'),
        ),
        migrations.AlterField(
            model_name='informediario',
            name='torre_fin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_fin', to='lineas.torre', verbose_name='Torre fin del día'),
        ),
        migrations.AlterField(
            model_name='informediario',
            name='torre_inicio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_inicio', to='lineas.torre', verbose_name='Torre inicio del día'),
        ),
        migrations.AlterField(
            model_name='informediario',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
        migrations.AlterField(
            model_name='informediario',
            name='vanos_ejecutados',
            field=models.PositiveIntegerField(default=0, help_text='Número de vanos completados en el día', verbose_name='Vanos ejecutados'),
        ),
        migrations.AlterField(
            model_name='programacionmensual',
            name='datos_importados',
            field=models.JSONField(blank=True, default=dict, validators=[apps.core.validators.datos_importados_validator], verbose_name='Datos importados'),
        ),
        migrations.AlterField(
            model_name='tipoactividad',
            name='campos_formulario',
            field=models.JSONField(blank=True, default=dict, help_text='Configuración de campos dinámicos en formato JSON', validators=[apps.core.validators.campos_formulario_validator], verbose_name='Campos del formulario'),
        ),
        migrations.AlterField(
            model_name='tipoactividad',
            name='categoria',
            field=models.CharField(choices=[('PODA', 'Poda de Vegetación'), ('HERRAJES', 'Cambio de Herrajes'), ('AISLADORES', 'Cambio de Aisladores'), ('INSPECCION', 'Inspección General'), ('LIMPIEZA', 'Limpieza'), ('SEÑALIZACION', 'Señalización'), ('MEDICION', 'Medición'), ('LAVADO', 'Lavado Tradicional'), ('SERVIDUMBRE', 'Servidumbre'), ('PERMISO', 'Gestionar Permiso'), ('CORREDOR', 'Corredor Eléctrico'), ('INSPECCION_PED', 'Inspección Pedestre'), ('TERMOGRAFIA', 'Termografía'), ('DESCARGAS', 'Descargas Parciales'), ('ELECTROMEC', 'Mtto Electromecánico'), ('MEDICION_PT', 'Medida Puesta Tierra'), ('OTRO', 'Otro')], max_length=20, verbose_name='Categoría'),
        ),
        migrations.AlterUniqueTogether(
            name='informediario',
            unique_together={('fecha', 'cuadrilla')},
        ),
    ]
